LevelImposter-Web/Controllers/MapController.cs
using LevelImposter.Models;
using LevelImposter.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LevelImposter.Controllers
{
    public class MapController : Controller
    {
        private LIService service;

        public MapController(LIContext context)
        {
            service = new LIService(context);
        }

        public IActionResult Index()
        {
            MapData[] maps = service.GetAllMaps();
            MapDataViewModel[] viewModels = new MapDataViewModel[maps.Length];
            for (int i = 0; i < viewModels.Length; i++)
            {
                viewModels[i] = new MapDataViewModel(maps[i]);
            }

            return View(viewModels);
        }

        public async void Download(string? id)
        {
            if (id == null)
                return;

            int realId = MapDataViewModel.StringToId(id);
            MapData map = service.GetMapById((int)realId);

            if (map == null)
            {
                RedirectToAction("Index");
                return;
            }


            byte[] data = Encoding.ASCII.GetBytes(map.Json);
            Response.Headers.Add("content-disposition", "attachment; filename=" + id + ".json");
            await Response.Body.WriteAsync(data, 0, data.Length);
        }

        public IActionResult Details(string? id)
        {
            if (id == null)
                return RedirectToAction("Index");

            int realId = MapDataViewModel.StringToId(id);
            MapData map = service.GetMapById((int)realId);

            if (map == null)
                return RedirectToAction("Index");

            return View(new MapDataViewModel(map));
        }

        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upload(MapData Map, IFormFile JsonFile)
        {
            // File Existance
            if (JsonFile == null)
            {
                ViewBag.Message = "File provided does not exist";
                return View();
            }

            // File Size
            if (JsonFile.Length > 100 * 1000000)
            {
                ViewBag.Message = "File size too big (100mb max)";
                return View();
            }

            var test = Path.GetExtension(JsonFile.FileName).ToLower();
            // File Type
            if (Path.GetExtension(JsonFile.FileName).ToLower() != ".json")
            {
                ViewBag.Message = "File provided was not a proper LevelImposter map file";
                return View();
            }
            
            // Decode
            using (Stream stream = JsonFile.OpenReadStream())
            {
                byte[] bytes = new byte[JsonFile.Length];
                stream.Read(bytes, 0, (int)JsonFile.Length);

                Map.Json = Encoding.ASCII.GetString(bytes);

               

                try
                {
                    Newtonsoft.Json.JsonConvert.DeserializeObject<MapTemplate>(Map.Json);
                    service.AddMap(Map);
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.Message = "File provided was not a proper LevelImposter map file";
                    return View();
                }
            }
        }
    }
}

LevelImposter-Web/Views/Map/Details.cshtml
@{
	ViewData["Title"] = "Map - Level Imposter";
}
@model LevelImposter.Models.MapDataViewModel

<div class="row">
	<div class="col-sm-6">
		<h2>@Model.Name</h2>
		<h5><b>Code: </b>@Model.Id</h5>
		<p>@Model.Description</p>
	</div>
	<div class="col-sm-6">
		<iframe src="/Home/Editor?id=@(Model.Id)&hidecontrols" class="map-embed"></iframe>
	</div>
</div>
<div class="row">
	<div class="col-sm-12">
		@Html.ActionLink("Download", "Download", "Map", new { id = Model.Id }, new { @class = "btn btn-primary" })
		<a href="/Home/Editor?id=@(Model.Id)" class="btn btn-info">Edit</a>
		@Html.ActionLink("Return", "Index", "Map", new { }, new { @class = "btn btn-danger" })
	</div>
</div>

LevelImposter-Web/Views/Map/Index.cshtml
@{
	ViewData["Title"] = "Map - Level Imposter";
}
@model LevelImposter.Models.MapDataViewModel[]

<h2>Recent Uploads</h2>

<div class="row">
	@for (int i = 2; i >= 0; i--)
	{
	<div class="col-sm-4">
		@for (int o = (int)Math.Min(Math.Ceiling(Model.Length / 3.0) * (i + 1), Model.Length) - 1; o >= (int)(Math.Ceiling(Model.Length / 3.0) * i); o--)
		{
			var map = Model[o];
			<div class="card mb-2">
				<div class="card-body">
					<h5 class="card-title">@map.Name</h5>
					<h6 class="card-title"><b>Code: </b>@map.Id</h6>
					<p class="card-text">@map.Description</p>
					@Html.ActionLink("Download", "Download", "Map", new { id = map.Id }, new { @class = "card-link" })
					@Html.ActionLink("More Details", "Details", "Map", new { id = map.Id }, new { @class = "card-link" })
				</div>
			</div>
		}
	</div>
	}
</div>

LevelImposter-Web/Views/Map/Upload.cshtml
@{
	ViewData["Title"] = "Map - Level Imposter";
}
@model LevelImposter.Models.MapData

@if (ViewBag.Message != null)
{
	<div class="alert alert-danger" role="alert">
		@ViewBag.Message
	</div>
}

@using (Html.BeginForm("Upload", "Map", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	<h2>Upload Map</h2>
	<hr />
	<div class="form-group">
		<h4>Name</h4>
		@Html.TextBoxFor(model => model.Name, new { @class = "form-control", required = string.Empty, placeholder = "Map Name" })
	</div>
	<div class="form-group">
		<h4>Description</h4>
		@Html.TextAreaFor(model => model.Description, new { @class = "form-control", required = string.Empty, placeholder = "Map Description" })
	</div>
	<div class="form-group">
		<h4>Upload</h4>
		<input id="JsonFile" name="JsonFile" type="file" required />
	</div>
	<div class="form-group">
		<button class="btn btn-primary m-1" type="submit">Upload</button>
		<a class="btn btn-danger m-1" asp-area="" asp-controller="Map" asp-action="Index">Cancel</a>
	</div>
}